project:
  type: website
  output-dir: docs

# Meta
description-meta: "Academic Website for Nicholas J. E. Richardson"
author-meta: "Nicholas Richardson"

website:
  title: "Nicholas J. E. Richardson"
  #image: "https://quarto.org/quarto.png"
  description: "Academic Website for Nicholas J. E. Richardson"

  navbar:
    background: dark

    left:
#      - text: Home
#        href: index.qmd
      - text: About
        menu:
          # - text: News
          #   href: posts.qmd#category=news
          # - text: Events
          #   href: posts.qmd#category=event
          - text: Affiliations
            href: affiliations.qmd
          - text: Contact
            href: contact.qmd
      - text: Research
        menu:
          - text: Publications
            href: publications.qmd
          # - text: Selected Papers
          #   href: posts.qmd#category=paper
          # - text: Presentations
          #   href: posts.qmd#category=presentation
      - text: Teaching
        href: teaching.qmd
      - text: Music
        href: music.qmd

    right:
      - text: CV
        href: files/Nicholas_Richardson_CV.pdf
      - icon: github
        href: https://github.com/njericha
        target: _blank

  page-navigation: true

  page-footer:
    left: "[Nicholas Richardson](https://njericha.github.io/) &copy; <script>document.write(new Date().getFullYear())</script>"
    center: "Built on [Quarto Academic Website Template](https://github.com/drganghe/quarto-academic-website-template) adapted by [Dr. Gang He](http://drganghe.github.io)"
    right:
      - icon: github
        href: https://github.com/njericha/njericha.github.io
        target: _blank

  search:
    location: navbar
    type: textbox

  reader-mode: true

  draft-mode: unlinked

  repo-url: https://github.com/njericha/njericha.github.io
#  repo-actions: [edit, issue, source]

  open-graph: true

  twitter-card: true
#  card-style: summary

  site-url: "https://njericha.github.io/"

  # google-analytics:
  #   tracking-id: ""  # Please delete or replace with your own tracking ID
  #   anonymize-ip: true

  drafts:
    - posts.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    footnotes-hover: true
    code-copy: true
    code-link: true
    code-overflow: wrap
    fig-align: center
    link-external-icon: false
    link-external-newwindow: true
    email-obfuscation: javascript
    link-external-filter: '^(?:http:|https:)\/\/njericha\.github\.io\'
    include-in-header: "files/includes/_academic.qmd"
