---
# title: "Presentations"
# description-meta: "Conference slides and other presentations given"
# title-block-banner: false
---

# Presentations

## Conferences, Seminars, and Workshops

**05 Jun 2026**: Multiscale Methods for Optimization of Discretized Continuous Functions, SIAM OP26, Edinburgh, Scotland, United Kingdom. [slides](files/presentations/05_jun_siam_op_2026.pdf)

**20 Jan 2026**: Optimization and Applications of Unsupervised Signal Demixing, SFU Operations Research Seminar, Burnaby, BC. [slides](files/presentations/20_jan_sfu_2026.pdf)

**10 Dec 2025**: Tucker-1 Demixing Model: Under the Hood, Geology Industry Training with Teck and BHP, Vancouver, BC. [slides](files/presentations/10_dec_geo_training_2025.pdf)

**30 Jul 2025**: BlockTensorDecomposition.jl: An Optimization Framework for Constrained Tensor
Factorization, Joint SIAM/CAIMS Annual Meetings 2025, Montréal, QC. [slides](files/presentations/30_jul_siam_2025.pdf)

**14 Jul 2025**: Unsupervised Signal Demixing with Tensor Factorization,
Vision and Learning Workshop at ICML 2025, Vancouver, BC.
[poster](files/posters/14_jul_icml_2025.pdf)

**02 Dec 2024**: Density Separation with Tensor Factorization,
2024 CMS Winter Meeting, Richmond, BC.
[slides](files/presentations/02_dec_cms_2024.pdf)

**20 Oct 2024**: Density Separation with Tensor Factorization,
2024 INFORMS Annual Meeting, Seattle, WA.
[slides](files/presentations/20_oct_informs_2024.html)

**21 Sep 2024**: Density Separation with Tensor Factorization, West Coast Optimization Meeting 2024, Vancouver, BC.
[slides](files/presentations/21_sep_wcom_2024.html)

**08 Jul 2024**: Density Separation with Tensor Factorization,
2024 SIAM Annual Meeting, Spokane, WA.
[slides](files/presentations/08_jul_siam_an24.html)

**14 Oct 2023**: Non-negative Tensor Decompositions for Unsupervised Learning, 4th
Biennial Meeting of SIAM Pacific Northwest Section, Bellingham, WA.
[slides](files/presentations/14_oct_siam_pnw_2023.pdf)

**01 Jul 2021**: Sparse Random Wavelet Representation & Decomposition, Canadian
Applied and Industrial Mathematics Society (CAIMS), Waterloo, ON.
Runner up in annual poster competition
[poster](files/posters/21_jun_caims_2021.pdf) [slides](files/presentations/01_jul_caims_2021.pdf) [website](https://uwaterloo.ca/canadian-applied-industrial-math-society-annual-meeting-2021/)

## Other Talks

**13 Apr 2026**: Signal Demixing with
Tensor Factorization, 2026 Institute of Applied Math Retreat, Vancouver, BC.
[slides](files/presentations/13_apr_iam_retreat_2026.pdf)

**11 Apr 2025**: Discretizing Constraints
at Multiple Scales, 2025 Institute of Applied Math Retreat, Vancouver, BC.
[slides](files/presentations/11_apr_iam_retreat_2025.pdf)

**04 Mar 2025**: Learning Gaussian Mixtures Using the Wasserstein-Fisher-Rao Gradient Flow, Machine Learning Reading Group, Vancouver, BC. [slides](files/presentations/04_mar_ml_reading_group_2025.html) [original paper](https://doi.org/10.1214/24-AOS2416)

**18 Feb 2025**: Mathematics of Music: Connections from harmonics to tuning, Math Graduate Seminar, Vancouver BC. [notes](files/presentations/13_feb_mgs_2025.pdf)

**15 Apr 2024**: Approximate Matrix Rank, 2024 Institute of Applied Math Retreat, Vancouver, BC.
[slides](files/presentations/15_apr_iam_retreat_2024.pdf)

**10 Oct 2023**: Tensor Decompositions, Optimization & Applications, Math Graduate Seminar, Vancouver BC.
